#!/userver/userver-test/build_release/venv-userver-default/bin/python
import os
import sys

import pytest

TESTSUITE_TESTS_PATH = '/userver/userver-test/testsuite'
TESTSUITE_WORKING_DIR = '/userver/userver-test/build_release'
TESTSUITE_PYTHONPATH = ['/usr/lib/cmake/userver/testsuite/pytest_plugins']
TESTSUITE_PYTEST_ARGS = ['--build-dir=/userver/userver-test/build_release',
 '--service-logs-file=/userver/userver-test/build_release/Testing/Temporary/service.log',
 '--basetemp=/userver/userver-test/build_release/Testing/Temporary',
 '--service-config=/userver/userver-test/configs/static_config.yaml',
 '--service-source-dir=/userver/userver-test',
 '--service-binary=/userver/userver-test/build_release/userver-samples-hello_service']


def testsuite_runner():
    args = [
        # Put path to test sources as the first argument to work around pytest issue #12802
        TESTSUITE_TESTS_PATH,
        *TESTSUITE_PYTEST_ARGS,
        *sys.argv[1:],
    ]
    os.chdir(TESTSUITE_WORKING_DIR)
    sys.path.extend(TESTSUITE_PYTHONPATH)
    os.environ['PATH'] = os.path.dirname('/userver/userver-test/build_release/venv-userver-default/bin/python') + ':' + os.environ['PATH']
    return pytest.main(args=args)


if __name__ == '__main__':
    sys.exit(testsuite_runner())
